const GeoData = {
  column: [
    { os: 'android 9', count: 3 },
    { os: 'os2', count: 13 },
    { os: 'os3', count: 3.5 },
    { os: 'os4', count: 5 },
    { os: 'os5', count: 4.9 },
    { os: 'os6', count: 6 },
    { os: 'os7', count: 7 },
    { os: 'os8', count: 9 },
    { os: 'os9', count: 13 },
    { os: 'android 9', count: 3 },
    { os: 'os2', count: 13 },
    { os: 'odds3', count: 3.5 },
    { os: 'ods4', count: 5 },
    { os: 'ods5', count: 4.9 },
    { os: 'osd6', count: 6 },
    { os: 'osd7', count: 7 },
    { os: 'osd8', count: 9 },
    { os: 'os9', count: 13 },
    { os: 'anddroid 9', count: 3 },
    { os: 'ods2', count: 13 },
    { os: 'dos3', count: 3.5 },
    { os: 'ods4', count: 5 },
    { os: 'ods5', count: 4.9 },
    { os: 'os6', count: 6 },
    { os: 'osd7', count: 7 },
    { os: 'os8', count: 9 },
    { os: 'os9', count: 13 },
    { os: 'adndroidd 9', count: 3 },
    { os: 'os2', count: 13 },
    { os: 'osd3', count: 3.5 },
    { os: 'osd4', count: 5 },
    { os: 'os5', count: 4.9 },
    { os: 'osd6', count: 6 },
    { os: 'os7', count: 7 },
    { os: 'os8d', count: 9 },
    { os: 'osd9', count: 13 },
  ],
};
export default GeoData;
